### ISSUE TITLE
Wrong Help for EtherCalc

### ISSUE THREAD

**Issue by RainerBielefeld** [wechange-eg/cosinnus-core#326]
### STR:  

0. Log in to wechange.de
1. Visit Pads for a Group or Project like [this one](https://wechange.de/group/testgruppe-24/document/testtabelle/)
2. Click on [Bearbeiten]  
   » Spreadsheet switches to Edit Mode
3. Click on [Hilfe] below spreasheet
   » Help appears. But it's Help for EtherPad, not for EtherCalc. There is nothing like "Uhrensymbol" for EtherCalc. 😥 

![230627_901_WrongEtherpadHelp](https://github.com/wechange-eg/cosinnus-core/assets/11803749/a957ea35-9ed6-4426-bfaa-5ef3a2689131)

And BTW, Help also is not correct for EtherPad. At least I can not find that "</>" for "share".

**Comment by saschasommer** [comment]
@RainerBielefeld thank you for the ticket! We will address the wrong help popup in an update in the near future!

**Comment by mko-x** [comment]
Fixed in latest release.

**Comment by RainerBielefeld** [comment]
Well, help has been dropped. Not the very best solution ...
