### ISSUE TITLE
Wrong Map Info for Braunschweig Weststadt

### ISSUE THREAD

**Issue by RainerBielefeld** [wechange-eg/cosinnus-core#327]
### STR:

1. Open a Task 
2. Do some entries
3. Open "Additional Options"
4. Into "Standort" Type (or copy / paste) "Braunschweig Weststadt"
   » as expected after few seconds map preview appears. 
    But the marker is outside [Weststadt](https://www.openstreetmap.org/relation/2414966#map=14/52.2520/10.4814)  😥
![grafik](https://github.com/wechange-eg/cosinnus-core/assets/11803749/4157e9a4-2753-4fd6-b7b5-8b8f24d65316)  
  
That would be a better place for the marker:  
![grafik](https://github.com/wechange-eg/cosinnus-core/assets/11803749/d76d4016-e1f5-4d2f-9d43-389c7c7091a6)
  
5. For Comparison try another place "Braunschweig Westliches Ringgebiet"
   » That will work fine with marker at a plausible place:  
  
![grafik](https://github.com/wechange-eg/cosinnus-core/assets/11803749/1b18c126-c143-4a5f-8bc9-89479c85fa30)

**Comment by saschasommer** [comment]
Hi @RainerBielefeld. We're using the OpenStreetMaps nominatim service to resolve the location for given location names, so I'm afraid we cannot do anything to change individual location results. Sorry!

**Comment by RainerBielefeld** [comment]
That info might help, I'm a hobby mapper at OSM ... We will have to fix that there.  Thx!

**Comment by RainerBielefeld** [comment]
Well, please see https://rocketchat.wechange.de/channel/wechange-support?msg=he5KZfXFaJkD4bXx6 with a reference to a discussion on Matrix. Result might be that Help for wechange.de should mention the difference between "Hannover, Lahe" and "Hannover Lahe" and other similar places.
