### ISSUE TITLE
Image loss when close Task from Task view

### ISSUE THREAD

**Issue by RainerBielefeld** [wechange-eg/cosinnus-core#444]
# My experience: 
_wechange.de Tasks_ will lose attached pictures when task will be closed form Task view. No problem when Task will be closed from Task list.
* I was able to reproduce the problem in [wechange.de](https://wechange.de/group/testgruppe-24/todo/testaufgabe-bildanhaenge-in-aufgaben-verschwi/). 
* First observed in suniversum.de, which also is affected. **[Here](https://suniversum.de/project/aufbau-digitale-vernetzung/todo/will-nur-mal-bildverbleib-klaeren/)** you find a detailed Step By Step Instruction in German Language.

**Comment by saschasommer** [comment]
@RainerBielefeld we have just released a fix and the issue you described should now be resolved! If there are any further problems, please let us know. Thank you for your detailed bug report!

**Comment by RainerBielefeld** [comment]
Thx!
I'll do some tests ASAP!
