### ISSUE TITLE
Matterbridge integration with Rocketchat

### ISSUE THREAD

**Issue by samuk** [wechange-eg/cosinnus-core#52]
Hi I'm wondering if it's possible to use Matterbridge with your instance of Rocketchat?

The use case would be to bring messages from an existing Slack channel into Rocketchat, and Rocketchat messages into an existing Slack Channel.

Refs
https://github.com/42wim/matterbridge
https://github.com/42wim/matterbridge/wiki/Section-RocketChat-%28basic%29
https://github.com/42wim/matterbridge/wiki/Slack-bot-setup

**Comment by saschan** [comment]
Hi @samuk,
right now we have no immediate plans to include any rocketchat integrations, although we are looking into how we can improve some aspects of our rocketchat instance in the middle of 2021. I will definitely keep matterbridge in mind for then!
